# Generated by Django 3.1 on 2020-12-30 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='movie',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='movie_community.movie', verbose_name='리뷰 단 영화'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review_comment',
            name='movie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='movie_community.movie'),
            preserve_default=False,
        ),
    ]
